name: Build and Release Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build Docker image
      run: |
        docker build -t arch-build .

    - name: Build package and create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker run --rm -v "$(pwd):/src" arch-build /bin/sh -c "cd /src && makepkg -srif && bash /src/.github/scripts/create_release.sh"
