name: build

on: [push, pull_request, workflow_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USER }}
          # Password or personal access token used to log against the Docker registry
          password:  ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arch Linux package
        uses: ./
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/.github/workflows/PKGBUILD
          OUTDIR: $HOME/arch-packages

      - name: Build the package again
        uses: ./
        with:
          BUILD_SCRIPT: extra-x86_64-build
          PKGBUILD: $GITHUB_WORKSPACE/.github/workflows/PKGBUILD
          OUTDIR: $HOME/arch-packages2

# See: https://github.com/taotieren/deepin-wine-qq-arch/blob/master/.github/workflows/main.yml
