# This is a basic workflow to help you get started with Actions
name: Build and Release Package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: arch-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo pacman -Sy --noconfirm base-devel git

    - name: Build package
      run: |
        makepkg -srif

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release of the package.
        draft: false
        prerelease: true

    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: '*.pkg.tar.zst'
    
    - name: Get artifact URL
      id: artifact_url
      run: |
        echo "::set-output name=URL::$(curl -s -X POST -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[0].archive_download_url')"
