name: Make ArchLinux Buildpkg

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo pacman -S --noconfirm base-devel git
        sudo pacman -S --noconfirm rust bindgen spirv-tools spirv-llvm-translator
        sudo pacman -S --noconfirm cmake meson expat
    - name: Build package
      run: |
        git clone https://github.com/DereckySany/make_archlinux_builldpkg.git
        cd make_archlinux_builldpkg
        makepkg -sri --noconfirm
