name: build

on: [push, pull_request, workflow_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Makepkg Build and Check
      - uses: edlanglois/pkgbuild-action@v1.1.8
        with:
          # Relative path to directory containing the PKGBUILD file.
          pkgdir: $GITHUB_WORKSPACE/.github/workflows/PKGBUILD
          # Additional arguments to pass to makepkg.
          makepkgArgs: "-march=native -mtune=native -m3dnow -m3dnowa -mfpmath=sse -Os"
