name: build

on: [push, pull_request, workflow_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USER }}
          # Password or personal access token used to log against the Docker registry
          password:  ${{ secrets.DOCKER_PASSWORD }}
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm base-devel git
      - name: Clone BUILDPKG repository
        run: |
          git clone https://github.com/DereckySany/make_archlinux_builldpkg.git
          cd make_archlinux_builldpkg
          git checkout main
      - name: Build BUILDPKG package
        run: |
          cd make_archlinux_builldpkg
          makepkg -sri --noconfirm
