name: Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Test
      run: |
        docker pull archlinux
        docker build -t arch-pkgbuilder .
        docker run -it --name arch-pkgbuilder-container arch-pkgbuilder
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arch-packages
        path: arch-packages
